package com.example.actividadfinalandroid.domain.use_case.draft

import com.example.actividadfinalandroid.domain.model.Task
import com.example.actividadfinalandroid.domain.model.TaskDraft
import com.example.actividadfinalandroid.domain.repository.DraftRepository
import com.example.actividadfinalandroid.domain.repository.TaskRepository
import javax.inject.Inject

class PublishDraftUseCase @Inject constructor(
    private val taskRepository: TaskRepository,
    private val draftRepository: DraftRepository
) {
    suspend operator fun invoke(draft: TaskDraft): Result<Unit> {
        val now = System.currentTimeMillis()
        val task = Task(
            id = "", // Will be generated by Firestore or repository
            ownerId = draft.ownerId,
            title = draft.title,
            description = draft.description,
            completed = false,
            createdAt = now,
            updatedAt = now
        )
        val result = taskRepository.createTask(task)
        if (result.isSuccess) {
            draftRepository.deleteDraft(draft)
        }
        return result
    }
}
